-- MySQL Script generated by MySQL Workbench
-- Tue Jun  8 09:51:56 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema accesoriossimple
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema accesoriossimple
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `accesoriossimple` DEFAULT CHARACTER SET utf8 ;
USE `accesoriossimple` ;

-- -----------------------------------------------------
-- Table `accesoriossimple`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`departamentos` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `region` ENUM('Caribe', 'Centro Oriente', 'Centro Sur', 'Eje Cafetero - Antioquia', 'Llano', 'Pacífico') NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`municipios` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `acortado` VARCHAR(60) NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  `departamento_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_municipios_departamentos1_idx` (`departamento_id` ASC) ,
  CONSTRAINT `fk_municipios_departamentos1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `accesoriossimple`.`departamentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(200) NOT NULL,
  `apellidos` VARCHAR(200) NOT NULL,
  `tipo_documento` ENUM('C.C', 'C.E', 'T.I', 'R.C', 'Pasaporte') NOT NULL,
  `documento` BIGINT NOT NULL,
  `telefono` BIGINT NOT NULL,
  `direccion` VARCHAR(105) NOT NULL,
  `municipio_id` BIGINT UNSIGNED NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `user` VARCHAR(100) NULL,
  `password` VARCHAR(150) NULL,
  `foto` VARCHAR(105) NULL,
  `rol` ENUM('Administrador', 'Empleado', 'Cliente', 'Proveedor') NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_municipios1_idx` (`municipio_id` ASC) ,
  CONSTRAINT `fk_usuarios_municipios1`
    FOREIGN KEY (`municipio_id`)
    REFERENCES `accesoriossimple`.`municipios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`compras` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_serie` VARCHAR(100) NOT NULL,
  `empleado_id` INT UNSIGNED NOT NULL,
  `proveedor_id` INT UNSIGNED NOT NULL,
  `fecha_compra` DATETIME NOT NULL,
  `monto` DOUBLE NOT NULL,
  `estado` ENUM('En progreso', 'Cancelada', 'Finalizada') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_compras_usuarios1_idx` (`empleado_id` ASC) ,
  INDEX `fk_compras_usuarios2_idx` (`proveedor_id` ASC) ,
  CONSTRAINT `fk_compras_usuarios1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `accesoriossimple`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_usuarios2`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `accesoriossimple`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`categorias` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`marcas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`marcas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`colors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`colors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(150) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`productos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `precio` DECIMAL NOT NULL,
  `porcentaje_ganancia` FLOAT NOT NULL,
  `stock` MEDIUMINT NOT NULL,
  `categoria_id` INT UNSIGNED NOT NULL,
  `marca_id` INT UNSIGNED NOT NULL,
  `color_id` INT UNSIGNED NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_productos_categorias1_idx` (`categoria_id` ASC) ,
  INDEX `fk_productos_marcas1_idx` (`marca_id` ASC) ,
  INDEX `fk_productos_colors1_idx` (`color_id` ASC) ,
  CONSTRAINT `fk_productos_categorias1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `accesoriossimple`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_marcas1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `accesoriossimple`.`marcas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_productos_colors1`
    FOREIGN KEY (`color_id`)
    REFERENCES `accesoriossimple`.`colors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`ventas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `numero_serie` VARCHAR(250) NOT NULL,
  `cliente_id` INT UNSIGNED NOT NULL,
  `empleado_id` INT UNSIGNED NOT NULL,
  `fecha_venta` DATETIME NOT NULL,
  `monto` DOUBLE NOT NULL,
  `estado` ENUM('En progreso', 'Cancelada', 'Finalizada') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ventas_usuarios1_idx` (`cliente_id` ASC) ,
  INDEX `fk_ventas_usuarios2_idx` (`empleado_id` ASC) ,
  CONSTRAINT `fk_ventas_usuarios1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `accesoriossimple`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_usuarios2`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `accesoriossimple`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`detalle_ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`detalle_ventas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `venta_id` INT UNSIGNED NOT NULL,
  `producto_id` INT UNSIGNED NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_venta` DOUBLE NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_ventas_productos1_idx` (`producto_id` ASC) ,
  INDEX `fk_detalle_ventas_ventas1_idx` (`venta_id` ASC) ,
  CONSTRAINT `fk_detalle_ventas_productos1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `accesoriossimple`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_ventas_ventas1`
    FOREIGN KEY (`venta_id`)
    REFERENCES `accesoriossimple`.`ventas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`fotos` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(60) NULL,
  `descripcion` TEXT NULL,
  `producto_id` INT UNSIGNED NOT NULL,
  `ruta` VARCHAR(120) NOT NULL,
  `estado` ENUM('Activo', 'Inactivo') NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fotos_productos1_idx` (`producto_id` ASC) ,
  CONSTRAINT `fk_fotos_productos1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `accesoriossimple`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `accesoriossimple`.`detalle_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `accesoriossimple`.`detalle_compras` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `producto_id` INT UNSIGNED NOT NULL,
  `compra_id` INT UNSIGNED NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_venta` DOUBLE NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalle_compras_productos1_idx` (`producto_id` ASC) ,
  INDEX `fk_detalle_compras_compras1_idx` (`compra_id` ASC) ,
  CONSTRAINT `fk_detalle_compras_productos1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `accesoriossimple`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_compras_compras1`
    FOREIGN KEY (`compra_id`)
    REFERENCES `accesoriossimple`.`compras` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
